file = open("myfile.txt", "r")
contents = file.read()
print(contents)
file.close()
file = open("myfile.txt", "w")
file.write("I have written a new code")
file.close()
file = open("myfile.txt", "r")
contents = file.read()
print(contents)
file.close()